# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2c4c0c6600bc9ace9e67249bc787569a16ee66e0a8652977d85f5990481981b9d37b4aa81f123970e5b77c70fcc847d359f12d5f363126453b1f233f8086a3

test:
  secret_key_base: b5057b0b616e77f1399056e6dcb96b996c242c7c29805c31700f4d11eda9dd588fce279214fd8b78197def9655cd88413559023b4b69c68253b247e0e4315aea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
